// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAktx10E28E_yhB8Whm7ejZCytaEnD-_Hg',
    appId: '1:887482621560:web:40b0c5af49da2bb4f8d78d',
    messagingSenderId: '887482621560',
    projectId: 'smayl-app',
    authDomain: 'smayl-app.firebaseapp.com',
    storageBucket: 'smayl-app.firebasestorage.app',
    measurementId: 'G-6FL0L55V4V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0vGJqnDsRxtFO_jArzaN19N5d6lnJVSI',
    appId: '1:887482621560:android:bafa169989b78338f8d78d',
    messagingSenderId: '887482621560',
    projectId: 'smayl-app',
    storageBucket: 'smayl-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_6OSiTpMh_Ii3ku1tkKFkXT2MDIW9hAM',
    appId: '1:887482621560:ios:f94ba48f708f3b0df8d78d',
    messagingSenderId: '887482621560',
    projectId: 'smayl-app',
    storageBucket: 'smayl-app.firebasestorage.app',
    iosBundleId: 'rlp.hoev.smayl.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAktx10E28E_yhB8Whm7ejZCytaEnD-_Hg',
    appId: '1:887482621560:web:fbe068f3af5b301df8d78d',
    messagingSenderId: '887482621560',
    projectId: 'smayl-app',
    authDomain: 'smayl-app.firebaseapp.com',
    storageBucket: 'smayl-app.firebasestorage.app',
    measurementId: 'G-9BQ62ZZZ18',
  );
}
